figure
subplot(2,2,1)
plot(-X1)
xlim([0,T])
xlabel('Days of trading')
title('Time Series Plot: Returns FTSE100')
subplot(2,2,3)
plot(abs(X1))
xlabel('Days of trading')
xlim([0,T])
title('Time Series Plot: Absolute Returns FTSE100')
subplot(2,2,2)
plot(-X2)
xlabel('Days of trading')
xlim([0,T])
title('Time Series Plot: Returns STOXX50E')
subplot(2,2,4)
plot(abs(X2))
xlabel('Days of trading')
xlim([0,T])
title('Time Series Plot: Absolute Returns STOXX50E')
%---------------------------------------------------------------
[par_arma_n_1, log_n_1, u_n_1, sig_n_1, res_n_1, v_n_1]=fitparm_n(X1,s);
[par_arma_n_2, log_n_2, u_n_2, sig_n_2, res_n_2, v_n_2]=fitparm_n(X2,s);
[par_arma_t_1, log_t_1, u_t_1, sig_t_1, res_t_1, v_t_1]=fitparm_t(X1,s);
[par_arma_t_2, log_t_2, u_t_2, sig_t_2, res_t_2, v_t_2]=fitparm_t(X2,s);
[par_arma_s_1, log_s_1, u_s_1, sig_s_1, res_s_1, v_s_1]=fitparm(X1,s);
[par_arma_s_2, log_s_2, u_s_2, sig_s_2, res_s_2, v_s_2]=fitparm(X2,s);
%---------------------------------------------------------------
figure
subplot(2,3,1)
plot(v_n_1{1})
xlim([0,T])
ylim([0,70])
xlabel('Days of trading')
title('Cond. Variance for FTSE100 - Normal')
subplot(2,3,4)
plot(res_n_1{1}./sqrt(v_n_1{1}))
xlabel('Days of trading')
xlim([0,T])
title('Stand. Residuals for FTSE100- Normal')
subplot(2,3,2)
plot(v_t_1{1})
xlabel('Days of trading')
xlim([0,T])
ylim([0,70])
title('Cond. Variance for FTSE100- T')
subplot(2,3,5)
plot(res_t_1{1}./sqrt(v_t_1{1}))
xlabel('Days of trading')
xlim([0,T])
title('Stand.Residuals for FTSE100 - T')
subplot(2,3,3)
plot(v_s_1{1})
xlabel('Days of trading')
xlim([0,T])
ylim([0,70])
title('Cond. Variance for FTSE100- SkewT')
subplot(2,3,6)
plot(res_s_1{1}./sqrt(v_s_1{1}))
xlabel('Days of trading')
xlim([0,T])
title('Stand.Residuals for FTSE100 - SkewT')
figure
subplot(2,3,1)
plot(v_n_2{1})
xlim([0,T])
ylim([0,40])
xlabel('Days of  trading')
title('Cond. Variance for STOXX50E - Normal')
subplot(2,3,4)
plot(res_n_2{1}./sqrt(v_n_2{1}))
xlabel('Days of trading')
xlim([0,T])
title('Stand. Residuals for STOXX50E- Normal')
subplot(2,3,2)
plot(v_t_2{1})
xlabel('Days of trading')
xlim([0,T])
ylim([0,40])
title('Cond. Variance for STOXX50E- T')
subplot(2,3,5)
plot(res_t_2{1}./sqrt(v_t_2{1}))
xlabel('Days of trading')
xlim([0,T])
title('Stand.Residuals for STOXX50E - T')
subplot(2,3,3)
plot(v_s_2{1})
xlabel('Days of trading')
xlim([0,T])
ylim([0,40])
title('Cond. Variance for STOXX50E- SkewT')
subplot(2,3,6)
plot(res_s_2{1}./sqrt(v_s_2{1}))
xlabel('Days of trading')
xlim([0,T])
title('Stand.Residuals for STOXX50E - SkewT')