T=2362;
figure
subplot(2,3,1)
plot(v_n_1)
xlim([0,T])
ylim([0,70])
xlabel('Days of trading')
title('Cond. Variance for S&P 500 - Normal')
subplot(2,3,4)
plot(res_n_1./sqrt(v_n_1))
xlabel('Days of trading')
xlim([0,T])
title('Stand. Residuals for S&P 500- Normal')
subplot(2,3,2)
plot(v_t_1)
xlabel('Days of trading')
xlim([0,T])
ylim([0,70])
title('Cond. Variance for S&P 500- T')
subplot(2,3,5)
plot(res_t_1./sqrt(v_t_1))
xlabel('Days of trading')
xlim([0,T])
title('Stand.Residuals for S&P 500 - T')
subplot(2,3,3)
plot(v_s_1)
xlabel('Days of trading')
xlim([0,T])
ylim([0,70])
title('Cond. Variance for S&P 500- SkewT')
subplot(2,3,6)
plot(res_s_1./sqrt(v_s_1))
xlabel('Days of trading')
xlim([0,T])
title('Stand.Residuals for S&P 500 - SkewT')


figure
subplot(2,3,1)
plot(v_n_2)
xlim([0,T])
ylim([0,40])
xlabel('Days of trading')
title('Cond. Variance for Nikkei - Normal')
subplot(2,3,4)
plot(res_n_2./sqrt(v_n_2))
xlabel('Days of trading')
xlim([0,T])
title('Stand. Residuals for Nikkei- Normal')
subplot(2,3,2)
plot(v_t_2)
xlabel('Days of trading')
xlim([0,T])
ylim([0,40])
title('Cond. Variance for Nikkei- T')
subplot(2,3,5)
plot(res_t_2./sqrt(v_t_2))
xlabel('Days of trading')
xlim([0,T])
title('Stand.Residuals for Nikkei - T')
subplot(2,3,3)
plot(v_s_2)
xlabel('Days of trading')
xlim([0,T])
ylim([0,40])
title('Cond. Variance for Nikkei- SkewT')
subplot(2,3,6)
plot(res_s_2./sqrt(v_s_2))
xlabel('Days of trading')
xlim([0,T])
title('Stand.Residuals for Nikkei - SkewT')